stages:
  - build
  - push
  - deploy

build:
  stage: build
  # tags:
  #   - docker-build
  script:
    - echo "Building Docker Image..."
    - docker --version
    - docker build -t $CI_REGISTRY_IMAGE .

push:
  stage: push
  # tags:
  #   - docker-build
  script:
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  script:
    # - ssh tls@192.168.1.200 "cd ./flaskapp && docker login -u '$CI_REGISTRY_USER' -p '$CI_JOB_TOKEN' '$CI_REGISTRY' && 
    #   docker compose pull flask-ui && docker compose up -d flask-ui && exit"
    - ssh tls@192.168.1.200 "cd ./flaskapp && docker compose pull flask-ui && docker compose up -d flask-ui && exit"    
